title = "Shubham Kumar"
baseURL = "https://example.com/"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Maharashtra, Pune"
email = "inbox.shubhamkumar@gmail.com"
favicon = "/favicon.ico"
firstName = "Shubham"
lastName = "Kumar"
phone = "+91-7599246005"
profileImage = "img/shubham.jpg"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showPublications = true
showQr = true
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/shubhamkumar143/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/sk-shubhamkumar"
name = "GitHub"

[[params.handles]]
link = "https://bitbucket.org/"
name = "Bitbucket"

[[params.handles]]
link = "https://stackoverflow.com/"
name = "Stack Overflow"

[[params.handles]]
link = "https://keybase.io/"
name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"